### PR TITLE
Added support to the alt attribute for images

### PR DESCRIPTION
**Pull request by maximzah**
When an image has an alt and lazy load than before loading we see the alt.
lazyload-bug-alt
I added logic for lazy load attribute `alt`. Now, `alt` will be added only after the load image.
Also, I updated tests and ran their, result: 
image

### CODE REVIEW

**Comment by verlok** [comment]
Quoting:

In order to make your images visible as soon as LazyLoad sets the src/srcset attribute to it, you can either:

Do it like that via CSS:

```css
/* Prevents img without src to appear */
img:not([src]) {
    visibility: hidden;
}
```

Or instead of the above :not() selector do it using the CSS classes of class_loading and class_loaded set by LazyLoad when loading starts or is completed.

**Comment by verlok** [comment]
What do you think?

**Comment by maximzah** [comment]
@verlok Yes, it is solving this problem.
But, sometimes users don`t want or can not to change CSS then the solution (this PR) for theirs.
Without this CSS it looks like the bug so maybe need to fix it in JS? What do you think about it?

**Comment by verlok** [comment]
Hey @maximzah, sorry for not answering before.
The alt attribute must be present in the html of the page, also for SEO reasons, so I wouldn't lazy load it.
To solve the problem, just hide the image until the `src` and `srcset` attributes are not set.

**Pull request closed without merging**
