### PR TITLE
Volatile

### PR DESCRIPTION
**Pull request by NathanMOlson**
I added a "volatile" class to the image declaration that prevents the image from being purged from the LazyLoad.  This allows it to be updated after it has been loaded the first time.

### CODE REVIEW

**Comment by verlok** [comment]
Hello and thank you very much for your work.

I'm not that into using classes for what is behaviour, so instead of `class="volatile"` I would prefer `data-volatile` or `data-volatile="true"`. In this way we could also remove the `_hasClass` function.

Anyway I can't understand what you're trying to achieve here. You wrote:

    I added a "volatile" class to the image declaration that prevents the image from being purged from the LazyLoad. This allows it to be updated after it has been loaded the first time.

Why do you need LazyLoad to update the image after it's been loaded the first time? Why can't you get the image and update it's src or srcset attribute?

**Comment by NathanMOlson** [comment]
OK, I've changed from using a class to using `data-volatile`.

Let me explain a little about my use case.

I have an embedded web server with two cameras, and a webpage that desplays the most recent image from the camera.  This image is updated about once a second.  I have been doing this by using javascript to change the `src` attribute.  However, this results in unnecessary network traffic if the image is off-screen.  I want to use lazyload to avoid unnecessary network traffic, but as of v 2.1.1 each image is loaded only once and then purged from the list of images.  I've added the `data-volatile` attribute to mark images that may be updated after they are loaded and may also be off-screen and not require immediate updating.

**Comment by NathanMOlson** [comment]
I added a check to see if a volatile image is already up-to-date before updating it.  This should improve performance.

**Comment by wesharey** [comment]
Thanks for your explanation. So you need to update your "camera" image only if it's on screen. This is a good idea! Anyway I think you are putting your code in the wrong place... I mean you're putting some logic that is only required by your application inside LazyLoad. 
What I would recommend is to do everything in your application, and just call LazyLoad's `_isInsideViewport()` function to check whether your image is inside viewport or not.

**Comment by verlok** [comment]
Sorry I have a commented logged as another user but it was me

**Comment by verlok** [comment]
What do you think?

**Comment by verlok** [comment]
Closing because of no reply

**Pull request closed without merging**
