### PR TITLE
Node support

### PR DESCRIPTION
**Pull request by klarstrup**
With these changes in place, simply importing `vanilla-lazyload` without using it won't crash Node by itself.

This is important for isomorphic/universal/server rendered setups where the same code runs on both the server and the browser. 

(My ulterior motive is that merging this will let us stop vendoring `vanilla-lazyload` over at https://github.com/shopgun/incito-browser and re-add it as a proper dependency)

### CODE REVIEW

**Comment by verlok** [comment]
Hey @klarstrup,
thank you for taking the time to do the fix. 
Do you have the chance to create the pull request towards a feature branch of my repo, or are you only able to pull request toward `master`?

**Comment by verlok** [comment]
Never mind, I’ve just found how to proceed here https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by verlok** [comment]
Done!

**Comment by verlok** [comment]
Do you need this in version 8.x too?

**Comment by klarstrup** [comment]
Good stuff man, keep up the great work!

**Comment by verlok** [comment]
Thanks! We open-source projects maintainers need kudos to keep up! 😄

**Pull request merged**
