### PR TITLE
bugfix: Cannot read property 'classList' of null thrown when js is loaded in head (even with async + defer)

### PR DESCRIPTION
**Pull request by ignatiusreza**
in our setup, all js are minified and concatenated into single js file and it is loaded with async + defer.. in some situation where the minified js is small enough, browser will finish loading and parsing it even before body is ready.. hence, call to `document.body` can sometime returns `null`..

### CODE REVIEW

**Comment by verlok** [comment]
Thank you for your pull request!

I might accept it if you:
- rename `_initialize` to `_isInitialized`
- change the version name (add 0.0.1)
- run the grunt task to generate the minified file

Thank you again for the fix!

**Comment by ignatiusreza** [comment]
updated as requested! 

> change the version name (add 0.0.1)

I assume that you're referring to version in `package.json`?

> run the grunt task to generate the minified file

https://github.com/verlok/lazyload/pull/11 change package name to `vanilla-lazyload`, so I have to rename it back to `lazyload` before running `grunt`.. is that expected?

**Comment by verlok** [comment]
Uhm... I didn't expect that. But the correct name of this package on bower and npm is vanilla-lazyload because lazyload was already taken. We can keep vanilla-lazyload in the package.json

**Comment by verlok** [comment]
Thank you. Please check that everything is working in the /demo files. :+1:

**Comment by ignatiusreza** [comment]
Thank you. Everything looks ok to me. :+1:

**Comment by Spone** [comment]
Hi, I have a similar issue. I'm including `lazyload` to my `application.js` bundle (with the Asset Pipeline, I'm on Ruby on Rails). When the JS is interpreted, the body is not yet ready, and I get the following error in my console:

    TypeError: document.body is null

I'm using version 10.3.1 of the vanilla-lazyload NPM package. I seems that the fix made by @ignatiusreza is no longer present in the newest version?

Can you help?

**Comment by Spone** [comment]
I noticed that `document.body` is used to detect the `classList` support.

Can you use this code instead? This fixes the issue for me.

    var supportsClassList = 'classList' in document.createElement('p');

**Comment by ignatiusreza** [comment]
@Spone we updated `lazyload` in our app yesterday, and got the same error.. was just about to submit a PR to fix it when I noticed your comment.. since you've found the solution, maybe you would like to submit it as a PR?

**Comment by Spone** [comment]
Here is my PR :)

**Comment by verlok** [comment]
Thank you guys. I've been travelling a lot in the past days and I couldn't look at your comments and PRs. Will do it soon.

**Pull request merged**
