### PR TITLE
Add Loading, Loaded and Error classes when neither img or iframe

### PR DESCRIPTION
**Pull request by FreshRob**
Use case
The ability so show a loading style before bg images is loaded

Implementation
Creates a dummy img tag, once loaded then sets the bg style.

Issues
1) Unable to get the tests to pass on master even after changing the Jest test location
2) How do you create lazyload.min.js as there is no step in grunt to produce it

Note
Feel free to take the enhancement and implement the way you feel it should be done

### CODE REVIEW

**Comment by verlok** [comment]
This is a clever solution to add classes to elements with background images!
But what if the image works in the `img` tag and fails in the `background-image` element or vice-versa, maybe because of a network problem? It could add the wrong class, don't you think it's risky?

**Comment by FreshRob** [comment]
@verlok If it fails in the img it will treat it as a failure and not set the background img. 
When testing there was not another network request for the background image as it pulls it straight from the browser cache so there should not be a network problem.

**Comment by verlok** [comment]
Sorry for my late replies, it's too hot here to code outside business hours :) I will consider this though, I promise

**Comment by verlok** [comment]
I'm still alive and thinking this is a good idea, even if I need to think this through. 
Sorry I was busy with the creation of version 9 and the TDD restoration :)

**Comment by verlok** [comment]
Hi @FreshRob,
I took a closer look to your PR and I think that the line:

```js
onLoadCallback = function(){ setSources(element, settings.data_srcset, settings.data_src); };
```

Would make the visual loading of the websites slower, because the `background-image` is assigned only when the image is completely loaded. I'm thinking about very slow connections: if the image source would immediately be set in the `background-image`, the users will start seeing the image as soon as the image format allows it (Progressive JPEG is especially good for this).

Isn't it another way to listen to the loaded event but without preventing the image source to be immediately set in the `background-image`?

**Comment by verlok** [comment]
@FreshRob any thoughts?

**Pull request closed without merging**
