### PR TITLE
Support for string values in rootMargin setting in IntersectionObserver

### PR DESCRIPTION
**Pull request by orballo**
Hi there!

While implementing `lazyload` in our project I needed to use different offsets for the horizontal and vertical axis. I noticed that the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)'s `rootMargin` setting allows a string value similar to the one used in CSS `margin` property, being able in this way to define the four different offsets.

So I changed the line where `threshold` setting is passed to `IntersectionObserver` and then just ran `npx gulp` to build the dist files.

I think this would make the library work differently between the `v8.x`  and the `v10.x`. I don't know if this is something that you want to avoid.

Let me know if you want me to make any change or maybe explain this behaviour in the docs if you finally want it merged 😄 

Great library by the way! 🙌

### CODE REVIEW

**Comment by verlok** [comment]
Hi @orballo,
thank you for this PR. 

Yes I’m concerned about retro-compatibility with version 8, but I also think that we can do some progressive enhancement / graceful degradation here :)

So I think I will merge your PR in and specify in the docs that the value can either be a string or a number, but it must be a number in version 8. 

Is there any better, more elegant way to do it? 
I can’t figure out any at this moment.

**Comment by verlok** [comment]
Hi again @orballo,

I've temporarily moved your code in the `feature/stringThreshold` branch because I have some doubts about it.

I've tried passing `"100vh"` to the `threshold` option but I got an error on Chrome when creating the new `IntersectionObserver`. The error message says:

```
Uncaught DOMException: Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.
```

So LazyLoad is now forcing the unit to be `px`, but if the only other option is `%` I'd add another option, e.g. `threshold_unit`, defaulting to `px` and changeable to `%`.

What do you think?
What is your use case?

**Comment by verlok** [comment]
schermata 2018-09-04 alle 22 11 29

**Comment by verlok** [comment]
Now I've changed the code in that branch adding the `threshold_unit` option as I wrote before.
The usage would be:

```js
var ll1 = new LazyLoad({
    elements_selector: ".lazy",
    threshold: 100,
    threshold_unit: "%"
});
```

Does this solve your use case?

**Comment by verlok** [comment]
Uhm this wouldn't solve the case where you want to pass different values to horizontal and vertical rootMargin.

It could accept an array of values in both `threshold` and `threshold_unit`, but it would be overcomplicated to use (and also to code). 

(use case, to obtain `{rootMargin: "5px 5% 5px 5%"}` you'd need to pass `{threshold: [50, 100], threshold_unit: ["%", "px"]}`

---

So maybe the best solution is:
- if the option is a string, use it "as is"
- otherwise, add `"px"` at the end of it

**Comment by verlok** [comment]
It's very similar to what you did, but I think `isNan` is scary because [it returns false on empty string and spaces](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN) 😓

**Comment by verlok** [comment]
I decided to create a new option and call it `thresholds`, in the end. I think it was less confusing, even if it is, a little, because it must be a string while `threshold` must be a number. 

Released on [10.17](https://github.com/verlok/lazyload/releases/tag/10.17.0) and already in the master branch.

**Comment by verlok** [comment]
Please take a look to the API doc in the README and tell me if you think it’s clear enough.

**Comment by orballo** [comment]
Hi @verlok!

Yes, it makes sense to avoid another validation, and yes, I think the new name and docs are less confusing than the previous one 😄 

Thank you very much!

**Pull request merged**
