### PR TITLE
Migrate to ES2015 syntax

### PR DESCRIPTION
**Pull request by ricardobrandao**
This addresses #36. 

The new minified file is greater then the previous one by 2KB because some babel extensions required for earlier browsers are included in the file. 

Feel free to ask any questions/make some suggestions.

Thanks,
Ricardo Brandão

### CODE REVIEW

**Comment by verlok** [comment]
Muito obrigado Ricardo!
Il take a look at your code as soon as I can.
Did you fork version 3.0.0 already?

**Comment by ricardobrandao** [comment]
De nada Verlok :)

Yes, this is after the current HEAD of your master.

I'm going to take another look at this because there are still some things to improve.

**Comment by ricardobrandao** [comment]
Btw, we can also distribute the minified version of the original (i.e. ES2015) source file which will work on modern browsers.

**Comment by verlok** [comment]
Desculpe Ricardo,
I didn't merge because you said you were to "take another look at this because there are still some things to improve".
Now this branch has conflict. Can you do the pull request towards a new branch?

**Comment by ricardobrandao** [comment]
Ciao Andrea,

I'll take a look at this over the weekend, thanks :)

**Comment by verlok** [comment]
Good to know, thank you.

**Comment by ricardobrandao** [comment]
Ciao Andrea,

I've fixed the conflicts. I've noticed that you exposed the private functions because of the tests. In ES2015 we can do that differently by exporting multiple modules (e.g. classes, functions) from one js file with the [```export statement```](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export).

**Comment by verlok** [comment]
Thank you

**Comment by verlok** [comment]
@ricardobrandao I just realized that I merged everything inside the master branch, but I was willing to take a better look at in on a local branch here. I branched your edits on a "es2015" branch, how can I rever things in the master branch (keeping the further changes that I made)?

**Comment by verlok** [comment]
@sensorario I really need to start using some branching strategy here! :)

**Comment by ricardobrandao** [comment]
@verlok you can either revert the merge or [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History). However, it is not advisable to [rewrite history](http://stackoverflow.com/a/1491022/3499186)! 

I can help you with that if you are willing to follow that road but may I ask why you want to revert those changes and move them to a different branch? From my experience, maintaining both branches will become cumbersome.

**Comment by verlok** [comment]
Hi, I just wanted to better review what we have in the main JavaScript file, because I saw in the transpiled file that we are creating global variables now...
Using different branches shouldn't be  i'll big problem, get manages them very well

**Comment by verlok** [comment]
I also wanted to export both the transpiled an the non transpiled version of the script, to give users the ability to import directly the ES2015 version,  which already works in some browsers.

**Comment by ricardobrandao** [comment]
1. I meant that, in this case, it would be kinda cumbersome to maintain both branches because we have all in one file and things where moved from their *original* place. Because of that, any change to the master branch will create conflicts that are annoying to resolve. About the globals: using the ES2015 syntax all is contained within the file and only Lazyload is exported. In the transpiled version, _now() and defaultSettings are also in the global context but we can fix that easily.

2. I agree with you and that was my original thought but I've kept things simple. Do you want me to do that?

**Comment by verlok** [comment]
1. we should fix the exported globals, since they can conflict with another script.
2. yes please, I'd be grateful if you did that.

Please work on the ES2015 branch I've created and published. In the master branch, I'd like to restore the latest stable and tested version.

**Comment by verlok** [comment]
I did it. I reverted your changes in the master branch, but now they exist on the es2015 branch. You can continue to work there. Don't worry about the merge, I'll handle it. I'm becoming an expert 🤣

**Comment by verlok** [comment]
Actually I think it's better to re-branch `es2015` off from the `development` branch, so we won't have issues later.
I'll develop all future releases and bugfixes starting a new branch off the `development` branch, and the migration to es2015 is a new release, so it must be branched off `development`. When it will be completed, we'll merge it back on the `development` branch, test it, document it, then release everything on the `master` branch.
@ricardobrandao Are you in?

**Pull request merged**
